### ISSUE TITLE
use content from jsforcats.com

### ISSUE THREAD

**Issue by max-mapper** [OpenTechSchool/js-beginners-1#3]
I wrote a very similar introduction to JS that has been very well received, it would be worth a read! 

http://jsforcats.com

the outline is:
- What is a programming language/JS?
- Don't be a scaredy cat
- Install chrome, open chrome console
- Create a string
- Variables
- Using functions
- How to learn more (MDN)
- Using js you found elsewhere
- Writing new functions
- Loops
- Arrays
- Recommended reading

what I have yet to implement:
- More looping examples
- Objects and JSON
- Grabbing stuff from other pages on the internet and displaying it
- How to use Github to find and share code

**Comment by xMartin** [comment]
I like your approach because you let people play more with the console. I also like that you do more with strings, even use them to explain what a function is and why you should use it. @marijnh's approach is more scientific (statement/expression) and I guess it depends on the individual student what works better. I remember that I had the idea to do more with strings whenever people had problems understanding the mathematical and graphical stuff. Depends on what you're more interested in. Also I like that you have screenshots. Helps a lot to check if everything works as expected.

Another interesting aspect is using libraries like underscore and teaching people how to find stuff like that. We don't have that in our curriculum and I don't think we should add it at this point. How about doing a short demo on that as an intro for day 2 maybe?

As each step of our current curriculum builds upon the previous step I'm not sure how we can integrate JS for Cats. But as coaches we can offer it as an alternative to individual students or just take an exercise from it when the original one is hard to get.

For the next workshop we can definitely adopt some things. And how about a German version "JavaScript für Katzen"? ;)

**Comment by xMartin** [comment]
Closing this as we're using JS for cats as a separate resource. We also created a few issues to add some ideas to this workshop.
